# Generated by Django 2.2.1 on 2019-10-02 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=10)),
                ('last_completed', models.DateTimeField(verbose_name='last completed')),
                ('wait_days', models.IntegerField(default=1)),
                ('asignee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Person')),
                ('schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Schedule'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
